[package]
name = "big-keys"
description = "Row key translation for big"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
readme = "readme.md"

[dependencies]
big-page.workspace = true

[dev-dependencies]
proptest = "1"
