[package]
name = "big-exec"
description = "Runs a planned query against big storage"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
readme = "readme.md"

[dependencies]
big-db.workspace = true
big-plan.workspace = true
big-pager.workspace = true

[dev-dependencies]
proptest = "1"
