// Copyright 2026 Bany
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//! Reading one HTTP/1.1 request off a socket.
//!
//! Untrusted bytes, so every length is checked before it is used and nothing is allocated on
//! the strength of a header a client wrote.

use crate::{Response, MAX_BODY, MAX_INTERNAL_BODY};
use std::io::Read;

/// Longest request line or header line accepted. A client that sends more is not talking to
/// this server in good faith.
const MAX_LINE: usize = 8 << 10;
/// Most headers accepted, so an endless header block cannot be used to hold a thread open.
const MAX_HEADERS: usize = 64;
/// Total bytes of header the server will retain.
///
/// The per-line and per-count caps alone allow `MAX_HEADERS * MAX_LINE` = 512 KiB, which was
/// harmless while headers were parsed and dropped and is not harmless now that they are kept.
/// A real client sends well under 8 KiB of header; anything past that is being sent at us on
/// purpose.
const MAX_HEADER_BYTES: usize = 16 << 10;

/// One parsed request: everything read off the socket before a route is chosen.
pub struct Request {
    /// The method, verbatim and uppercase as sent.
    pub method: String,
    /// Path only, already split from the query string.
    pub path: String,
    /// The query string, without the `?`, unparsed.
    pub query: String,
    /// The body, bounded by [`crate::MAX_BODY`] - or by [`crate::MAX_INTERNAL_BODY`] on an
    /// `/internal/` route, whose body is binary and was generated by a peer rather than sent
    /// by a client.
    ///
    /// Bytes rather than a `String`. It used to be text, which was right while every route
    /// took text; the fan-out between nodes carries encoded containers, and validating those
    /// as UTF-8 on the way in would refuse them. Routes that want text ask for it with
    /// [`Request::text`] and get the same refusal they always did, one step later.
    pub body: Vec<u8>,
    /// Kept in arrival order, names lowercased. A `Vec` rather than a map because the whole
    /// point of the cap above is that this is short, and a linear scan over a dozen entries
    /// beats hashing them.
    pub headers: Vec<(String, String)>,
}

/// Why a request could not be read. Each maps to one status, and never to a `500`: nothing
/// here is the server's fault.
#[derive(Debug)]
pub enum RequestError {
    /// The bytes were not a request this parser accepts. The string says which part failed.
    Malformed(&'static str),
    /// A header block or body past its cap. Refused mid-read rather than buffered first.
    TooLarge,
    /// The socket failed underneath us - usually a client that hung up mid-request.
    Io(std::io::Error),
    /// The client closed cleanly *before* sending anything.
    ///
    /// Not a failure and not answerable: there is nobody left to answer. It exists because a
    /// kept-alive connection ends this way every time, and reporting that as a malformed
    /// request would put a `400` in the log for every well-behaved client that finished.
    Closed,
}

impl RequestError {
    /// The response to send back. Read failures are answered rather than logged and dropped,
    /// so a client sending malformed bytes learns which part was malformed.
    pub fn into_response(self) -> Response {
        match self {
            Self::TooLarge => Response::too_large(),
            Self::Malformed(m) => Response::bad_request(m),
            Self::Io(_) | Self::Closed => Response::bad_request("could not read the request"),
        }
    }
}

impl From<std::io::Error> for RequestError {
    fn from(e: std::io::Error) -> Self {
        Self::Io(e)
    }
}

impl Request {
    /// Reads one request off a reader.
    ///
    /// Every limit is enforced *during* the read, not after it: the header block, the line
    /// length, the header count and the body are each refused at the point they are exceeded,
    /// so a hostile client cannot make the server buffer what it is about to reject.
    ///
    /// A reader rather than the socket, and the caller keeps it between requests. A buffered
    /// reader built here and dropped at the end would take the front of the *next* request
    /// with it, which is invisible until a client pipelines and then loses a request for no
    /// reason it could ever find.
    pub fn read(reader: &mut impl Read) -> Result<Self, RequestError> {
        let start = read_line(reader)?;
        let mut parts = start.split(' ');
        let (Some(method), Some(target)) = (parts.next(), parts.next()) else {
            return Err(RequestError::Malformed("malformed request line"));
        };
        let (path, query) = match target.split_once('?') {
            Some((p, q)) => (p.to_string(), q.to_string()),
            None => (target.to_string(), String::new()),
        };

        let is_internal = path.starts_with("/internal/");
        let mut length = 0usize;
        let mut headers = Vec::new();
        let mut header_bytes = 0usize;
        for _ in 0..MAX_HEADERS {
            let line = read_line(reader)?;
            if line.is_empty() {
                let mut body = vec![0u8; length];
                reader.read_exact(&mut body)?;
                return Ok(Self { method: method.to_string(), path, query, body, headers });
            }
            header_bytes += line.len();
            if header_bytes > MAX_HEADER_BYTES {
                return Err(RequestError::TooLarge);
            }
            if let Some((name, value)) = line.split_once(':') {
                if name.eq_ignore_ascii_case("content-length") {
                    length = value
                        .trim()
                        .parse()
                        .map_err(|_| RequestError::Malformed("bad content-length"))?;
                    // Checked before the allocation, not after it.
                    //
                    // An `/internal/` body gets the larger ceiling because it is not a
                    // stranger's: it is what this cluster made of a request that already
                    // passed the public one, and the binary encoding of a batch of facts can
                    // be larger than the text it was parsed from. A client cannot reach these
                    // routes with anything a coordinator did not send, because a coordinator
                    // is the only thing that speaks to them.
                    let cap = if is_internal { MAX_INTERNAL_BODY } else { MAX_BODY };
                    if length > cap {
                        return Err(RequestError::TooLarge);
                    }
                }
                headers.push((name.trim().to_ascii_lowercase(), value.trim().to_string()));
            }
        }
        Err(RequestError::Malformed("too many headers"))
    }

    /// The body as text, or the refusal a client that sent something else has earned.
    ///
    /// Every route that takes text goes through here, so "the body is not UTF-8" is one
    /// message in one place rather than a check each of them could forget.
    pub fn text(&self) -> Result<&str, RequestError> {
        core::str::from_utf8(&self.body)
            .map_err(|_| RequestError::Malformed("body is not valid UTF-8"))
    }

    /// The value of one query-string parameter, if present.
    pub fn param(&self, name: &str) -> Option<&str> {
        self.query
            .split('&')
            .filter_map(|pair| pair.split_once('='))
            .find(|(k, _)| *k == name)
            .map(|(_, v)| v)
    }

    /// One header by name, case-insensitively. First occurrence wins: a request that sends
    /// `Authorization` twice is not one whose second value should be trusted over its first.
    pub fn header(&self, name: &str) -> Option<&str> {
        self.headers.iter().find(|(k, _)| k == name).map(|(_, v)| v.as_str())
    }

    /// Whether the client asked to keep the connection open.
    ///
    /// **Opt-in, which is not what HTTP/1.1 says.** A persistent connection holds a worker from
    /// a fixed pool, so the default here is the one that cannot starve it: a client that says
    /// nothing gets what it has always got, one request and a close. The fan-out between nodes
    /// asks for keep-alive explicitly, which is the traffic that pays for it - and even then
    /// the server refuses when too many workers are already holding one open.
    pub fn wants_keep_alive(&self) -> bool {
        self.header("connection").is_some_and(|v| v.eq_ignore_ascii_case("keep-alive"))
    }

    /// The bearer token, if the request carries one. Only the `Bearer` scheme is understood;
    /// anything else is treated as absent rather than half-parsed.
    pub fn bearer(&self) -> Option<&str> {
        let value = self.header("authorization")?;
        let (scheme, token) = value.split_once(' ')?;
        scheme.eq_ignore_ascii_case("bearer").then(|| token.trim())
    }

    /// Path split on `/`, empty segments dropped.
    pub fn segments(&self) -> Vec<&str> {
        self.path.split('/').filter(|s| !s.is_empty()).collect()
    }
}

/// One CRLF-terminated line, bounded so a client cannot stream forever without a newline.
fn read_line(reader: &mut impl Read) -> Result<String, RequestError> {
    let mut line = Vec::new();
    let mut byte = [0u8; 1];
    while line.len() < MAX_LINE {
        if reader.read(&mut byte)? == 0 {
            // Nothing at all had arrived: the client finished with this connection rather than
            // sending half a request. Told apart from a truncated line because only one of the
            // two is worth an answer.
            if line.is_empty() {
                return Err(RequestError::Closed);
            }
            break;
        }
        if byte[0] == b'\n' {
            if line.last() == Some(&b'\r') {
                line.pop();
            }
            return String::from_utf8(line)
                .map_err(|_| RequestError::Malformed("header is not valid UTF-8"));
        }
        line.push(byte[0]);
    }
    Err(RequestError::Malformed("header line too long"))
}
